name: Vanessa
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'Vanessa!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.11073023593053222
  lightness: 0.37068759254179895
  saturation: 0.498718491056934
  rhythmicContrast: 0.18215722916647792
purpose: []
